// <auto-generated />
namespace DoShineMP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddModelsfFor040 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModelsfFor040));
        
        string IMigrationMetadata.Id
        {
            get { return "201601110316412_AddModelsfFor040"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
